# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# gazelle:prefix simulator.code/receive-request
load("@rules_go//go:def.bzl", "go_library", "go_test")
load("//build:gomock.bzl", "go_mock_library")

go_library(
    name = "receive-request",
    srcs = ["receiver.go"],
    importpath = "simulator.code/receive-request",
    visibility = ["//visibility:public"],
    deps = [
        "//cloud_simulation/orchestrator/receive-request/firestore",
        "//cloud_simulation/orchestrator/receive-request/pubsub",
        "//cloud_simulation/orchestrator/receive-request/storage",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "receive-request_test",
    srcs = ["receiver_test.go"],
    embed = [":receive-request"],
    deps = [
        ":mock",
        "//cloud_simulation/orchestrator/receive-request/pubsub",
        "@com_github_stretchr_testify//assert",
        "@org_uber_go_mock//gomock",
    ],
)

go_mock_library(
    name = "mock",
    src = "receiver.go",
    importpath = "simulator.code/receive-request/mock",
    deps = [
        "//cloud_simulation/orchestrator/receive-request/pubsub",
    ],
)
