# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gazelle//:def.bzl", "gazelle")
load("@rules_shellcheck//:def.bzl", "shellcheck_test")
load("//tools:tools.bzl", "tool_binary")

gazelle(
    name = "gazelle",
    prefix = "simulator.code",
)

alias(
    name = "go",
    actual = "@rules_go//go",
)

tool_binary(
    name = "buildifier",
    tool = "@com_github_bazelbuild_buildtools//buildifier",
)

shellcheck_test(
    name = "bazel_run_shellcheck_test",
    size = "small",
    data = [
        "bazel-run.sh",
    ],
    format = "gcc",
    severity = "style",
    tags = ["lint"],
)
